package com.betoniarze.predihome.presentation.theme

import androidx.compose.ui.graphics.Color

/**
 * Light palette
 */
val LIGHT_PRIMARY = Color(0xFFA75827)
val LIGHT_PRIMARY_ALT = Color(0xFF927F7F)
val LIGHT_INVERSE_PRIMARY = Color(0xFFB3A59D)
val LIGHT_ON_PRIMARY = Color(0xFFFEFDED)
val LIGHT_SECONDARY = Color(0xFFB78B63)
val LIGHT_SECONDARY_ALT = Color(0xFF9A907F)
val LIGHT_ON_SECONDARY = Color(0xFFEBEBDB)
val LIGHT_BACKGROUND = Color(0xFFFFFEED)
val LIGHT_BACKGROUND_ALT = Color(0xFF2D2618)
val LIGHT_ON_BACKGROUND = Color(0xFF6E7673)
val LIGHT_ON_BACKGROUND_ALT = Color(0xFFEAC7A1)
val LIGHT_SURFACE = Color(0xBFBEBBB3)
val LIGHT_ON_SURFACE = Color(0xFF727876)


/**
 * Dark palette
 */
val DARK_PRIMARY = Color(0xFFA75827)
val DARK_PRIMARY_ALT = Color(0xFF927F7F)
val DARK_INVERSE_PRIMARY = Color(0xFF898481)
val DARK_ON_PRIMARY = Color(0xFFFEFDED)
val DARK_SECONDARY = Color(0xFFB78B63)
val DARK_SECONDARY_ALT = Color(0xFF9A907F)
val DARK_ON_SECONDARY = Color(0xFFEBEBDB)
val DARK_BACKGROUND = Color(0xFFFFFEED)
val DARK_BACKGROUND_ALT = Color(0xFF2D2618)
val DARK_ON_BACKGROUND = Color(0xFF6E7673)
val DARK_ON_BACKGROUND_ALT = Color(0xFFEAC7A1)
val DARK_SURFACE = Color(0xBFBEBBB3)
val DARK_ON_SURFACE = Color(0xFF727876)